### ISSUE TITLE
depviz v0: single page rendering

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#1]
I think the first step to make depviz a reality is to make a single page app that does all the following, entirely from clientside:

### v0 requirements

- Github only, but make it ready for other things.
- Leverage approach in https://github.com/jbenet/random-ideas/issues/37 and https://github.com/noffle/github-dependency-crawl to use the github issue comments themselves to store the dependency data 
  - this has the side benefit of making this data addable via email :) )
- single page app
- entirely client-side (i.e. no server or database needed whatsoever).
- crawl the graph via the website's api
  - (optimization) could use local-storage to cache crawls.

### Pieces we have

- graphviz and https://github.com/mstefaniuk/graph-viz-d3-js
- waffle, trello, and others as examples on info to add to the cards
- waffle as an example of a system that works off github API.
- [noffle/github-dependency-crawl](https://github.com/noffle/github-dependency-crawl) to fetch the dep graph of an issue.
- [jbenet/issue-dep-graph](https://github.com/jbenet/issue-dep-graph) to turn an issue into dot output
- Product mocks over at https://github.com/jbenet/depviz/raw/master/mocks/

From here we just need to [draw the rest of the owl](http://i.imgur.com/RadSf.jpg):

- [x] App scaffold (React), as described in #3
- [x] A `DepsView` as described in #2 and in mocks.

---

depends on #2 
depends on #3 
depends on #4
depends on #5
depends on #6
depends on #7
depends on #8
depends on #9

**Comment by wking** [comment]
Is this missing a `depends on #7`?  #7 is in the same boat as #4, #5, and #6, but maybe you're intentionally excluding it from the v0 requirements?

**Comment by jbenet** [comment]
I was excluding it, but now that we have it, i've added it :) 👍

**Comment by wking** [comment]
All the dependencies for this are closed, so I'm closing this issue (which will clear out a large chunk of the github.com/jbenet/depviz graph ;).  Feel free to spin off new issues for outstanding requirements / improvements.

**Comment by jbenet** [comment]
fantastic! :) 👍
