### ISSUE TITLE
Logos -- ideas

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#14]
@wking asked bout logo ideas. So here are some.

I think we should have something:
- that is a good logo (scales well, recognizable, simple, etc)
- with 1-2 colors
- that evokes tasks (check boxes? a list?)
- that evokes dependencies (something graphy!)
- that evokes progress (progress bar?)
- that works well in a hex
  - actually, wonder how deps would show up in a hex grid...

dont need to meet all constraints, just some thoughts. i'll add some inspiration images below.

---

depends on #51

**Comment by jbenet** [comment]
![](http://www.ellmen.com/img/portfolio/git-logo-256x256.png)
![](https://wiki.icinga.com/download/attachments/131074/global.logo?version=7&modificationDate=1375951525000&api=v2)
![](https://blogs.endjin.com/wp-content/uploads/2014/04/tooManyNews_thumb.png)
![](http://openwebbeans.apache.org/resources/images/logo.png)
![](https://blog.rootshell.be/wp-content/uploads/2014/03/dependencies.png)
![](https://cdn5.f-cdn.com/contestentries/740792/3468177/57bedb9c6854d_thumb900.jpg)
![](https://lh5.googleusercontent.com/-_LM1gn4z_OA/VRC-DIznfCI/AAAAAAAAAeU/mrnWQkQfNGU/s256-no/Depends_256.png)
![](https://www.owasp.org/images/e/e9/Dependency-Track-logo-large.png)
![](http://assets.reviews.com/uploads/2015/09/25002300/ML_logo_lb-primary.png)
![](https://community.uservoice.com/wp-content/uploads/trello-logo.png)
![](http://www.fedena.com/blog/wp-content/uploads/2015/07/Redbooth-Logo.jpg)
![](http://c767204.r4.cf2.rackcdn.com/1e3276ca-3974-43d3-9dc6-9816d7ff8014.png)
![](http://www.sharepointsystems.co.za/images/Article_Images/Task-manager-logo-jpg.jpg)
![](http://www.empresasenred.es/empresasenred/sites/default/files/ThingsLogo.png)
![](http://seeklogo.com/images/A/asana-logo-1B7111BDA4-seeklogo.com.png)
![](https://confluence.atlassian.com/jiracorecloud/files/800697409/802161795/1/1454304601917/jiracore_rgb_blue.png)
![](http://cdn.toptenreviews.com/rev/prod/ce/66874-asana-box.jpg)
![](https://d13yacurqjgara.cloudfront.net/users/7528/screenshots/1158654/youtasklogo_teaser.png)

**Comment by jbenet** [comment]
@em-ly i think this may be a really good task for the Protocol Labs illustrators?

**Comment by jbenet** [comment]
## Possibility

### Alternatively, if we go with a simple representation of the depviz card + indicators, something like this:

![depviz1](https://cloud.githubusercontent.com/assets/138401/20587797/30af7b86-b1c5-11e6-96b5-793d7dcfb264.jpg)


### We can then put it into hexes like this:

![depviz2](https://cloud.githubusercontent.com/assets/138401/20587798/327c8a08-b1c5-11e6-8c3d-41c6c16fdbf9.jpg)

### Which tessellates into this:

![depviz3](https://cloud.githubusercontent.com/assets/138401/20587801/343a3872-b1c5-11e6-8db3-25a687ce6028.jpg)

**Comment by jbenet** [comment]
![depviz0](https://cloud.githubusercontent.com/assets/138401/20588091/5ebc45ac-b1c7-11e6-906d-5157772c2167.png)
![depviz0-bw](https://cloud.githubusercontent.com/assets/138401/20588092/5fdefa92-b1c7-11e6-9670-b667a15008f8.png)
![depviz0-bw2](https://cloud.githubusercontent.com/assets/138401/20588093/6155dc24-b1c7-11e6-9845-7e9348fde8ae.png)

**Comment by jbenet** [comment]
i like the electron-shell-ness

**Comment by jbenet** [comment]
### same-- but without numbers

![depviz1-color](https://cloud.githubusercontent.com/assets/138401/20588188/315db612-b1c8-11e6-96e3-05f5d16d4ba4.png)
![depviz1-bw](https://cloud.githubusercontent.com/assets/138401/20588189/3276cc28-b1c8-11e6-9fb3-e20220aff525.png)
![depviz1-bw2](https://cloud.githubusercontent.com/assets/138401/20588190/339d3aba-b1c8-11e6-8c73-a3c080a79962.png)

**Comment by jbenet** [comment]
![depviz1-bw3](https://cloud.githubusercontent.com/assets/138401/20588409/ad23e8a6-b1c9-11e6-9445-706f1ff5bca9.png)
![depviz1-bw4](https://cloud.githubusercontent.com/assets/138401/20588410/ad240e94-b1c9-11e6-8680-fedaa13bda1c.png)

**Comment by wking** [comment]
An option with fewer transitions:

![depviz](https://cloud.githubusercontent.com/assets/209920/20588574/11d38490-b1cb-11e6-9aed-e841ffa7b3fa.png)

**Comment by jbenet** [comment]
i like! it feels a bit too heavy. maybe reducing size will help. or using a lighter gray.

btw, for those aiming to try, i used the font: `Helvetica Neue`

**Comment by jesseclay** [comment]
but can we get some more hexes

**Comment by wking** [comment]
I've pushed an SVG of the [simple form][1] into #11 so we can drop the React logo.  If folks with better design sense want to point me at a different SVG, I'm happy to swap it in ;).

[1]: https://github.com/jbenet/depviz/issues/14#issuecomment-262699118

**Comment by em-ly** [comment]
Started designers on the logo design: https://github.com/protocol/design-collaborations/issues/4

**Comment by em-ly** [comment]
Here are the logo designs we've received from one of the designers:

**Option 1**
![](https://cloud.githubusercontent.com/assets/22168118/20838249/0553a7a2-b8a8-11e6-90c7-3912d314a9e6.png)

![](https://cloud.githubusercontent.com/assets/22168118/20838254/0a8ef6ae-b8a8-11e6-9215-852f46eb559c.png)


**Option 2**

![](https://cloud.githubusercontent.com/assets/22168118/20838267/1ce3cb9a-b8a8-11e6-81a3-eff3be4baf8e.png)

![](https://cloud.githubusercontent.com/assets/22168118/20838270/1f95a50c-b8a8-11e6-9bae-4a66a39466c2.png)


**Option 3**

![](https://cloud.githubusercontent.com/assets/22168118/20838618/a178a7c6-b8a9-11e6-9bbb-031fd2ac02fc.png)

![](https://cloud.githubusercontent.com/assets/22168118/20838621/a368fcca-b8a9-11e6-908f-a14924f9a836.png)


**Option 4**

![](https://cloud.githubusercontent.com/assets/22168118/20838307/479687b0-b8a8-11e6-806e-3b9b523043ff.png)

![](https://cloud.githubusercontent.com/assets/22168118/20838317/4ce9feb8-b8a8-11e6-9260-54b1e3d04624.png)

**Comment by wking** [comment]
I like 4 (checks and graphs :).

**Comment by jbenet** [comment]
I'm gonna drop my comments in the protocol design issue

**Comment by jbenet** [comment]
@wking do you want access to that?

**Comment by wking** [comment]
> @wking do you want access to that?

There are probably enough folks involved already; I'd just be more noise ;).  As long as an SVG (and [maybe][1] a good/neutral/bad palette? #49) comes out the other side, I'll be happy.

[1]: https://github.com/jbenet/depviz/issues/49#issuecomment-264698488

**Comment by em-ly** [comment]
Here are the second iterations of logos based off of the feedback from the last batch:
![d038f302-bc84-11e6-9737-9b6e6e22a4da](https://cloud.githubusercontent.com/assets/19555738/21413596/86739fb8-c7c6-11e6-8967-9d2fb38e7d76.png)

![c9f73eea-bc84-11e6-8b8b-8933fc1ddbc2](https://cloud.githubusercontent.com/assets/19555738/21413598/87d5478a-c7c6-11e6-8e65-fb3ff50b0427.png)

![c39fad48-bc84-11e6-89ca-0f4002f9f2e1](https://cloud.githubusercontent.com/assets/19555738/21413599/896a67a6-c7c6-11e6-968c-2aa9175f7ebb.png)

![faac7528-bc84-11e6-849d-8ffc1872886b](https://cloud.githubusercontent.com/assets/19555738/21413600/8c8d93ae-c7c6-11e6-8672-1ac33043a7d1.png)

**Comment by wking** [comment]
I'm still partial to the graph v.  Recursive hexes are cute, but I
don't think we're going to actually use hex-shaped dep-indicators
(some other non-circle shapes are on the table, #61).  On the palette
front, I don't have a strong preference, and the issues to balance
are:

* Red/green is a traditional stop-go color scheme [1].
* Red/green is a terrible choice for a colorblind-friendly UI [2].

[1]: https://github.com/jbenet/depviz/issues/49#issuecomment-264698488
[2]: https://github.com/jbenet/depviz/issues/49#issuecomment-265392776

**Comment by wking** [comment]
Fixed by #72.
