### ISSUE TITLE
Make Object DepsView

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#2]
This is the view that visualizes a given object.

- [x] is associated with an object, via its URI
- [x] crawls the object for the dep graph, up to some depth (2-3 hops? configurable?)
- [x] turns the graph into dot
- [x] uses graphviz-d3-js to turn dot into a d3 thing.
- [x] renders the dep graph on the view.
- [x] can click another node to re-center and traverse the graph there. separate re-rendering.
- [x] nodes should be basic waffle-like cards, as in the mocks UX.
  - card subitems (comments, labels, assignees, title, etc) should link correctly (as in waffle)
  - Wonder if there's an open source trello-like thing to leverage here.
- [ ] shows [expanded view](https://github.com/jbenet/depviz/raw/master/mocks/images/depviz.mocks.007.jpg).
- [x] shows [collapsed view](https://github.com/jbenet/depviz/raw/master/mocks/images/depviz.mocks.011.jpg).

---

depends on #8
depends on #9
depends on #10
depends on #11

**Comment by jbenet** [comment]
depends on #8
depends on #9
depends on #10

**Comment by wking** [comment]
#11 does all of this except for expanded cards.

The graph-traversal is wired up a bit differently, with an initial async fetch for all the nodes, graphviz layout on the fly as each node is added, and subsequent scrolling around (via mouse or touch drags) without any further network or graphviz activity.  Fetching the graph (even nodes that are far offscreen) may lead to performance issues, but we want to be caching these nodes in local storage anyway, each node is small, and we don't expect *that* many nodes in the graph ;).  Still, it should be possible to check on each addition to see how far from the viewBox the node is before deciding whether to immediately fetch its dependencies.

**Comment by jbenet** [comment]
sounds good-- i'll close this for now. we can track the ExpandedView in #8

**Comment by jbenet** [comment]
> Still, it should be possible to check on each addition to see how far from the viewBox the node is before deciding whether to immediately fetch its dependencies.

yeah makes sense.
