### ISSUE TITLE
Enable travis-ci

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#23]
- [x] enable on https://travis-ci.org/jbenet/depviz (@jbenet)
- [ ] add a travis.yml file that builds + tests things correctly

---

depends on #29

**Comment by wking** [comment]
On Mon, Nov 28, 2016 at 12:44:10PM -0800, Juan Benet wrote:
> - [ ] add a travis.yml file that builds + tests things correctly

I can work on this tonight if nobody beats me to it.  Locally I've
been running:

  $ npm test -- --coverage

and checking for 100% success and line coverage.  The npm test harness
likes ncurses, but I imagine there is some way to get at those results
programmatically.
