### ISSUE TITLE
Make App Scaffold

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#3]
- [ ] single-page React app, all client-side
- [ ] make the home route

---

the routes will look like this:

```
/  - home, bit of info on depviz. lets you enter/paste an address to visualize.

/http/github.com/<user>/<repo>/issues/<issue> - viz single issue, + 2-3 hops
/http/github.com/<user>/<repo>/pull/<pr>      - viz single issue, + 2-3 hops
/http/github.com/<user>/<repo>                - try to visualize the whole graph of a repo?
```

- We use `/http` prefix to ensure we can use other protocols later.
- We use `/http/github.com` prefix to ensure we can use other websites later.
- We use `/http/<github-link-to-thing>` to match their API well and allow users to easily paste links.

---
depends on #11

**Comment by jbenet** [comment]
Using https://github.com/facebookincubator/create-react-app

**Comment by wking** [comment]
Done in #11.  Can we either add a `depends on #11` or merge #11 and close this?
