### ISSUE TITLE
Add a status checkbox to displayed cards

### ISSUE THREAD

**Issue by wking** [jbenet/depviz#39]
GitHub doesn't seem to expose this on issue results, but we can use the API [here][1].  For example:

```
$ curl https://api.github.com/repos/jbenet/depviz/commits/refs/pull/35/head/status
{
  "state": "success",
  "statuses": [
    {
      "url": "https://api.github.com/repos/jbenet/depviz/statuses/7f5536da1cddd9010dcac3f62afc12f5110cab6d",
      "id": 888186845,
      "state": "success",
      "description": "The Travis CI build passed",
      "target_url": "https://travis-ci.org/jbenet/depviz/builds/180569146",
      "context": "continuous-integration/travis-ci/pr",
      "created_at": "2016-12-01T23:49:38Z",
      "updated_at": "2016-12-01T23:49:38Z"
    }
  ],
  "sha": "7f5536da1cddd9010dcac3f62afc12f5110cab6d",
  …
}
```

[1]: https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

---

depends on #69

**Comment by jbenet** [comment]
Oh, nice! yeah!

**Comment by wking** [comment]
Trying to come up with a display for this, I think we may want to drop our current right column:

![current](https://cloud.githubusercontent.com/assets/209920/20858026/ad65e2a6-b8ef-11e6-8d09-72fecf662289.png)

to be a fourth row:

![bottom-row](https://cloud.githubusercontent.com/assets/209920/20858029/b33043fc-b8ef-11e6-85f9-26b876beb338.png)

That gives us more space for multiple people and longer IDs/titles, keeps the cards at a reasonable size, and doesn't crowd too much.  The CI-status icon is in the lower right, and I was thinking of icons like:

* success: ✓ (U+2713, CHECK MARK)
* failure: ✗ (U+2717, BALLOT X) or ⚠ failure (U+26A0, WARNING SIGN)
* in progress: ● (U+25CF, BLACK CIRCLE), ⏲ (U+23F2, TIMER CLOCK), or • (U+2022, BULLET)

The in-progress U+25CF is a bit heavy in black, but would probably feel more appropriately sized in amber.

Does anything in there sound good?  Do folks have other ideas for how CI-status should look?

**Comment by wking** [comment]
I'm just going to go ahead with the design floated above^.  We can always adjust later if folks want to shuffle the card contents.
