### ISSUE TITLE
Auto-deploy for github pages?

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#40]
Could we hook up a travis bot to build + deploy to github pages? or what's the best way to do this?

---

depends on #42

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 05:00:30PM -0800, Juan Benet wrote:
> Could we hook up a travis bot to build + deploy to github pages? or
> what's the best way to do this?

I think you can give Travis a token to do it for you, but I'm fine
doing it manually (we're not going *that* fast ;).  I've just deployed
master now.

**Comment by jbenet** [comment]
hm-- may be good because that way i can merge and check from phone.

Some docs with examples:
- https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
- https://benlimmer.com/2013/12/26/automatically-publish-javadoc-to-gh-pages-with-travis-ci/
- https://github.com/jirutka/rake-jekyll

@VictorBjelkholm thoughts?

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 09:59:02PM -0800, Juan Benet wrote:
> hm-- may be good because that way i can merge and check from phone.

Ok.  Travis docs on encrypting settings are in [1].  Can
you create a token [2] with public_repo scope, encrypt it with the
travis gem, and paste it in here?

  $ gem install travis
  $ travis encrypt ${TOKEN}

Then we'll want a deploy entry for their GitHub Pages deploy provider
[3,4].

  deploy:
    provider: pages
    github_token:
      secure: …that encrypted variable…
    local_dir: webapp/build
    skip_cleanup: true
    on:
      branch: master

Docs for `on:` are in [5].  It's possible we need:

  deploy:
    provider: pages
    edge: true
    …

for the GitHub Pages provider.

[1]: https://docs.travis-ci.com/user/encryption-keys
[2]: https://github.com/settings/tokens
[3]: https://docs.travis-ci.com/user/deployment/#Adding-a-Provider
[4]: https://github.com/travis-ci/dpl#github-pages
[5]: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by wking** [comment]
[1] is the testbed for the new-in-October pages provider
(travis-ci/dpl#501), so it looks like my .travis.yml guess was pretty
close ;).

[1]: https://github.com/webknjaz/dpl-gh-pages/blob/master/.travis.yml

**Comment by jbenet** [comment]
Oooof, i have to give it Write access to _every public repo_? i cant do that for security reasons. Let me see if there's a way to do it for this single repo. (Wow. github is seriously asking for it.)

**Comment by wking** [comment]
On Thu, Dec 01, 2016 at 11:31:52PM -0800, Juan Benet wrote:
> Oooof, i have to give it Write access to _every public repo_?

Well, you *could* create a depviz-only user, add them as a
collaborator, and have *them* grant the token ;).  But I agree that it
would be better for GitHub to support more granular scoping.

**Comment by jbenet** [comment]
Encrypted token:

```yml
secure: "CREvCtbgvsLTC7nCFD5FZbo5F3PwcoEnzCHLmVYeTYWvW8RbAN4oWx28V8fVW/GZq3Gt4gniF9HMKSE+eCe2+d/6+l1UPFbHLGdUangXjdnsLkoBNEm2HdyO5k3NpVCPoK6pIcuOGLaLjqxX7ctKGvjkjOGKwfpsbfCGyUzwOB65wF5jzlQ4uY0luYBKF2tuwd+YS7tB9Sc4Wv2u12BpHGFX7GGMkTDEKklCNhfDcRxBgaJn922WGvXZNae0yhs986BjztooCNyiB1fJthRpG95haITX5/ucJ33EyBOe5ZbLEwgBxYQxKSu0/LJ8pfQn2JTowxABkqG9YePyPNmPbMVdiWT4NKinPR7eDxXXgiNT0M/sHOdD+TVUVNDS6MFg7RJeFOB1XU0us8OgdLx5eu0KHMnXSb87DxARSi78JWKPkpNsp+cDD16ey98el9pNkvqYC3TkthA4NMMOdaMt4b7QHgLDuqtJSY6N9h1iv5cGzNTHhKsDvJURz07jwVSrXpnpn/U0tMaT7B3CguP0uofLCkp5M15d9cLxBHaCoMF6sZmheybfHryHX2OOphIMMLC0BNigFT+tHDTbxY072vOAhLHb6u1RKw53wDZipm1RF6S+bAk/fL79jbjt3NtFKGtn4paBeZ/rLDq1y70Oh8nk7jgOJ6UeCMOBivDwXXY="
```

**Comment by jbenet** [comment]
@wking i think you understand the deploy step much better
