### ISSUE TITLE
Dependencies not rendering after they're done?

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#53]
Not sure if this became some toggle, but im not seeing the deps once they're completed:

![2016-12-04 at 9 09 pm](https://cloud.githubusercontent.com/assets/138401/20874357/e96b456c-ba65-11e6-8742-8dc6f98281ee.png)

**Comment by jbenet** [comment]
Maybe it's just that the issue is done. I dont see it in https://jbenet.github.io/depviz/#/http/github.com/jbenet/depviz 

i would personally really like to see the issues that are closed. why?
- want to see all of the issues to understand the breadth of the project
- the growing green-ness would fill me with great motivation: lots of progress being made \o/

(this is why i think the n-hop limit makes sense. show all deps up to n hops.)

We could play with these modes.

**Comment by wking** [comment]
On Sun, Dec 04, 2016 at 09:12:29PM -0800, Juan Benet wrote:
> Maybe it's just that the issue is done.

Yup [1].  I think we can close this issue as covered by #17 and #13,
with the goal being to make the graph-walking strategy configurable
(#34).

[1]: https://github.com/jbenet/depviz/issues/17#issuecomment-263361118
