### ISSUE TITLE
Authenticated Github User

### ISSUE THREAD

**Issue by VictorBjelkholm** [jbenet/depviz#58]
Would be nice for the future to have some area where you could leave your access code to different services (starting with Github) and it'll remember it, and use it when requesting things from the APIs, so private repositories and such would be visible as well.

---

depends on #34
depends on #67

**Comment by wking** [comment]
On Wed, Dec 07, 2016 at 02:43:46AM -0800, ᴠɪᴄᴛᴏʀ ʙᴊᴇʟᴋʜᴏʟᴍ wrote:
> Would be nice for the future to have some area where you could leave
> your access code to different services (starting with Github) and
> it'll remember it…

The GitHub-API library we use makes that easy [1], but we a
configuration UI to let the user pass that into the app (#34).
Putting submitted credential in local storage would be pretty
straightforward, and agents should be protecting anything stored there
[2].

[1]: http://github-tools.github.io/github/examples/authorization
[2]: https://www.w3.org/TR/webstorage/#sensitivity-of-data
