### ISSUE TITLE
Add App Route: Github User

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#7]
Make this route work:

```
/http/github.com/<user>
```
This would show all issues assigned to the user.

---

depends on #3 
depends on #11

**Comment by jbenet** [comment]
depends on #3

**Comment by wking** [comment]
Done in #11, although I don't walk later result pages yet (unless that happens internally in [`github-api`][1]?).  Can we either add a `depends on #11` or merge #11 and close this?

[1]: https://github.com/github-tools/github
