### ISSUE TITLE
CollapsedDepCardView

### ISSUE THREAD

**Issue by jbenet** [jbenet/depviz#9]
This is the view of a _collapsed card_.

It must have:

- [x] An "ID" segment 
  - [x] website logo
  - [x] local shorthand identifier
- [x] Progress bar, if any (based on the count, just rendered as the background filling up the bar). #18
- [x] 3 Dependency Indicators (dependencies, related, dependents)
- [x] Edge should change color depending on whether it's done (green) or not (red).

---

The cards on:

![](https://github.com/jbenet/depviz/raw/master/mocks/images/depviz.mocks.011.jpg)

---

depends on #11 
depends on #18

**Comment by jbenet** [comment]
Progress

![2016-11-20 at 4 14 am](https://cloud.githubusercontent.com/assets/138401/20462646/2b585e2c-aed8-11e6-9b5b-dddf80bcf3c0.png)

**Comment by jbenet** [comment]
smaller

![2016-11-20 at 4 25 am](https://cloud.githubusercontent.com/assets/138401/20462713/5978d06a-aed9-11e6-97ab-de295207f5ff.png)

**Comment by jbenet** [comment]
Progress bar on card

![2016-11-20 at 4 36 am](https://cloud.githubusercontent.com/assets/138401/20462799/ed894aea-aeda-11e6-976d-3b368653bb0c.png)

**Comment by wking** [comment]
#11 handles all of this except the progress bar.  GitHub doesn't seem to expose the task-list counts in their API and I haven't worked up or found a Markdown scraper to figure those counts out on our own.  Can we add a `depends on #11` for the other portions of this issue?

**Comment by VictorBjelkholm** [comment]
Guess as a first pass you can just look for occurrences of `[]` and `[ ]` and for completed ones look for `[x]`

**Comment by wking** [comment]
I'm working on the progress bar now.

**Comment by wking** [comment]
Progress bar landed via #18, so we've checked all the boxes for this issue.
